package com.clickflow.android.realtap

/**
* A single, one-shot request to dispatch a real tap via the AccessibilityService.
*
* Step 62 — Single Real Tap Prototype.
*
* Restrictions enforced by construction and by [RealTapController]:
*   - Exactly ONE tap per request. No repeat. No loop. No batched coordinates.
*   - Coordinates are in raw screen pixels and MUST come from a user-driven UI
*     gesture (e.g. an on-screen marker drag). They are never generated by code,
*     never read from OCR, never read from MediaProjection.
*   - [durationMs] is bounded to a single short press (50..250 ms). The default
*     is 80 ms, which mirrors a normal finger tap.
*   - Every request is tied to an in-memory [sessionId]. Sessions never persist.
*
* This is a request — it does NOT itself cause a tap. The user must additionally:
*   1. Have passed the safety review in this app session.
*   2. Have granted the Accessibility service.
*   3. Have confirmed the per-tap consent dialog immediately before dispatch.
*/
data class RealTapRequest(
   val x: Int,
   val y: Int,
   val durationMs: Long = 80L,
   val sessionId: String,
   val originLabel: String = "user_marker",
) {
   init {
       require(x >= 0) { "x must be >= 0" }
       require(y >= 0) { "y must be >= 0" }
       require(durationMs in MIN_DURATION_MS..MAX_DURATION_MS) {
           "durationMs must be in [$MIN_DURATION_MS, $MAX_DURATION_MS]"
       }
       require(sessionId.isNotBlank()) { "sessionId must be non-blank" }
   }

   companion object {
       const val MIN_DURATION_MS: Long = 50L
       const val MAX_DURATION_MS: Long = 250L
       const val DEFAULT_DURATION_MS: Long = 80L
   }
}

/**
* Reasons a real-tap request can be rejected or fail.
*
* BLOCKED_* values come from the safety gate (request never reaches the service).
* DISPATCH_* values come from the service itself.
*/
enum class RealTapOutcome {
   /** The service successfully dispatched the gesture. */
   DISPATCH_SUCCEEDED,

   /** The OS reported the gesture completed but did not deliver to the target. */
   DISPATCH_CANCELLED,

   /** The service was bound but dispatchGesture() returned false / threw. */
   DISPATCH_FAILED,

   /** Real taps are globally disabled by SafetyGate (canRunRealTapSingleProto = false). */
   BLOCKED_BY_GATE,

   /** Accessibility service is not enabled or not connected. */
   BLOCKED_ACCESSIBILITY_DISABLED,

   /** Safety review checklist has not been completed in this session. */
   BLOCKED_SAFETY_REVIEW_NOT_PASSED,

   /** User has not confirmed the per-tap consent dialog (or it expired). */
   BLOCKED_NO_FRESH_CONSENT,

   /** Device API level is below 24 (AccessibilityService.dispatchGesture). */
   BLOCKED_API_TOO_LOW,

   /** A real-tap session is not active. */
   BLOCKED_NO_SESSION,
}

/**
* The result of a [RealTapRequest]. Always returned synchronously from the
* controller — callers do not have to handle a callback to know whether the
* tap was dispatched.
*
* [happenedAtMs] is the wall-clock timestamp when the controller decided the
* outcome. [blockedReasons] is non-empty when [outcome] is one of the BLOCKED_*
* values, otherwise empty.
*/
data class RealTapResult(
   val outcome: RealTapOutcome,
   val request: RealTapRequest,
   val happenedAtMs: Long,
   val blockedReasons: List<String> = emptyList(),
) {
   val isDispatched: Boolean get() = outcome == RealTapOutcome.DISPATCH_SUCCEEDED
   val isBlocked: Boolean
       get() = outcome.name.startsWith("BLOCKED_")
}
